#!/bin/bash
#$ -S /bin/bash
#$ -N qmc                       # name of the job
#$ -cwd                         # run script in current directory                
#$ -pe orte2 28                 # use 28 MPI cores
#$ -q new.q                     # run job in big or new queue

export OMP_NUM_THREADS=1
ulimit -c 0

BIN=/home/petocchif/1_GW_EDMFT/1_gw_fp_NEW/GenericMaterial/Solver/bin

mpiexec -np 28 ${BIN}/ct_hyb input_qmc.in ./ > report 2>err

