#!/bin/bash
#$ -S /bin/bash
#$ -N Fe_08                     # job name
#$ -cwd                         # run script in current directory
#$ -pe smp 28                   # MPI cores
#$ -q new.q


export OMP_NUM_THREADS=1
ulimit -c 0




################################################################################
#                                USER SETTINGS                                 #
################################################################################
#COMPULSORY
GENMAT=/home/petocchif/1_GW_EDMFT/nobackup/1_production

PATH_INPUT=GWinput_SPEX_bccFe
PATH_DATA=Results_beta08

START_IT=0
END_IT=11

#OPTIONAL FOR TEMPERATURE DEPENDENT CALCULATIONS
PATH_INPUT_TR=GWinput_mats




################################################################################
#                             AUTO-SETUP SETTINGS                              #
################################################################################
LOCAL=$(pwd)
BINqmc=${GENMAT}/Solver/bin
BINsc=${GENMAT}/SelfConsistency/bin

if [ -z ${PATH_INPUT_TR+x} ]; then PATH_INPUT_TR=${PATH_INPUT} ; fi

export l0=`grep -n "PATH_INPUT=" input.in    | awk -F  ":" '{print $1}'`
export l1=`grep -n "PATH_INPUT_TR=" input.in | awk -F  ":" '{print $1}'`
export l2=`grep -n "PATH_DATA=" input.in     | awk -F  ":" '{print $1}'`
export l3=`grep -n "START_IT=" input.in      | awk -F  ":" '{print $1}'`
export l4=`grep -n "LAST_IT=" input.in       | awk -F  ":" '{print $1}'`

`sed -i ${l0}'s/'"PATH_INPUT=.*!"'/'"PATH_INPUT=${PATH_INPUT}         !"'/' input.in`
`sed -i ${l1}'s/'"PATH_INPUT_TR=.*!"'/'"PATH_INPUT_TR=${PATH_INPUT_TR}         !"'/' input.in`
`sed -i ${l2}'s/'"PATH_DATA=.*!"'/'"PATH_DATA=${PATH_DATA}         !"'/' input.in`
`sed -i ${l4}'s/'"LAST_IT=.*!"'/'"LAST_IT=${END_IT}         !"'/' input.in`




################################################################################
#                             SELF-CONSISTENCY LOOP                            #
################################################################################

for IT in `seq ${START_IT} 1 ${END_IT}`
do

   #
   IT_DATA=${LOCAL}/${PATH_DATA}/${IT}/
   `sed -i ${l3}'s/'"START_IT=.*!"'/'"START_IT=${IT}         !"'/' input.in`

   #
   # Lattice problem
   ${BINsc}/SelfConsistency > report_sc_it${IT} 2> err_sc_it${IT}
   mv {report_sc_it${IT},err_sc_it${IT}} ${IT_DATA}

   #
   # Impurity problem
   if [ -f "doSolver" ]; then
      rm doSolver
      mpiexec -np ${NSLOTS} ${BINqmc}/ct_hyb used.input.in ${IT_DATA} > report_qmc_it${IT} 2> err_qmc_it${IT}
      mv {report_qmc_it${IT},err_qmc_it${IT}} ${IT_DATA}
   else
      break
   fi

done
