#!/bin/bash
#$ -S /bin/bash
#$ -N TestOld                   # job name
#$ -cwd                         # run script in current directory
#$ -pe orte2  112               # MPI cores
#$ -q new.q                     # queue

export OMP_NUM_THREADS=1
ulimit -c 0

LOCAL=$(pwd)
BINqmc=/home/petocchif/1_GW_EDMFT/1_gw_fp_NEW/GenericMaterial/Solver/bin
BINsc=/home/petocchif/1_GW_EDMFT/1_gw_fp_NEW/GenericMaterial/SelfConsistency/bin

export l1=`grep -n "PATH_INPUT=" input.in | awk -F  ":" '{print $1}'`
export l2=`grep -n "PATH_DATA=" input.in | awk -F  ":" '{print $1}'`
export l3=`grep -n "START_IT=" input.in | awk -F  ":" '{print $1}'`
export l4=`grep -n "LAST_IT=" input.in | awk -F  ":" '{print $1}'`




################################################################################
#                                USER SETTINGS                                 #
################################################################################

PATH_INPUT=GWinput_SrMoO3
PATH_DATA=Results_SrMoO3

START_IT=0
END_IT=10

`sed -i ${l1}'s/'"PATH_INPUT="'/'"PATH_INPUT=${PATH_INPUT}  !"'/' input.in`
`sed -i ${l2}'s/'"PATH_DATA="'/'"PATH_DATA=${PATH_DATA}  !"'/' input.in`
`sed -i ${l4}'s/'"LAST_IT="'/'"LAST_IT=${END_IT}  !"'/' input.in`




################################################################################
#                             SELF-CONSISTENCY LOOP                            #
################################################################################

for IT in `seq ${START_IT} 1 ${END_IT}`
do
   #
   IT_DATA=${LOCAL}/${PATH_DATA}/${IT}/
   #
   # Lattice problem
   `sed -i ${l3}'s/'"START_IT="'/'"START_IT=${IT}  !"'/' input.in`
	${BINsc}/SelfConsistency  > report_sc_it${IT} 2> err_sc_it${IT}
   mv {report_sc_it${IT},err_sc_it${IT}} ${IT_DATA}
   #
   # Impurity problem
   if [ -f "doSolver" ]; then
      rm doSolver
      mpiexec -np 112 ${BINqmc}/ct_hyb input.in ${IT_DATA} > report_qmc_it${IT} 2> err_qmc_it${IT}
      mv {report_qmc_it${IT},err_qmc_it${IT}} ${IT_DATA}
   fi
   #
done
