#!/bin/bash
#$ -S /bin/bash
#$ -N qmc_test                  # name of the job
#$ -cwd                         # run script in current directory                
#$ -pe orte2 28                   # use 28 MPI cores
#$ -q new.q                     # run job in big or new queue

export OMP_NUM_THREADS=1
ulimit -c 0


mpiexec -np 28 ./Solver_ct_hyb input_file.DAT Iteration/ > report 2>err

